/**
 * Every piece of user-facing copy lives here (docs/sdd/12-ui-ux-guidelines.md).
 * Phase 1 ships a single locale, but keeping the text out of components means a
 * second locale would be a lookup change rather than a codebase-wide extraction.
 */
export const strings = {
  app: {
    name: 'Agency Hub',
    loading: 'Carregando…',
    retry: 'Tentar novamente',
    genericError: 'Não foi possível concluir a ação. Tente novamente.',
    networkError: 'Não foi possível falar com o servidor. Verifique sua conexão.',
    logout: 'Sair',
  },
  login: {
    title: 'Entrar',
    subtitle: 'Acesse com as credenciais fornecidas pela agência.',
    email: 'E-mail',
    password: 'Senha',
    submit: 'Entrar',
    submitting: 'Entrando…',
    noAccountHelp: 'Esqueceu a senha? Peça uma nova ao administrador da agência.',
  },
  changePassword: {
    title: 'Defina uma nova senha',
    forcedSubtitle: 'Sua senha atual é temporária. Escolha uma nova senha para continuar.',
    currentPassword: 'Senha atual',
    newPassword: 'Nova senha',
    confirmPassword: 'Confirme a nova senha',
    submit: 'Salvar nova senha',
    submitting: 'Salvando…',
    mismatch: 'As senhas não conferem.',
    success: 'Senha alterada com sucesso.',
  },
  home: {
    title: 'Início',
    welcome: (name: string) => `Olá, ${name}.`,
    roleLabel: 'Perfil',
    companiesLabel: 'Empresas com acesso',
    noCompanies: 'Nenhuma empresa vinculada ainda.',
  },
  dashboard: {
    question: 'O que precisa da sua atenção agora',
    filters: 'Filtros',
    allCompanies: 'Todas as empresas',
    anyResponsible: 'Qualquer responsável',
    from: 'De',
    to: 'Até',
    priority: 'Prioridade',
    productionStatus: 'Produção',
    clear: 'Limpar filtros',
    activeCompanies: 'Empresas ativas',
    today: 'Hoje',
    overdue: 'Atrasados',
    inProduction: 'Em produção',
    awaitingApproval: 'Aguardando aprovação',
    requestsAwaitingClient: 'Pendências com o cliente',
    requestsOverdue: 'Pendências vencidas',
    pendingPublications: 'A publicar',
    campaigns: 'Campanhas com atenção',
    unread: 'Não lidas',
    todayContent: 'Conteúdos de hoje',
    overdueContent: 'Conteúdos atrasados',
    overdueRequests: 'Pendências vencidas',
    recentFiles: 'Arquivos recentes',
    recentActivity: 'Últimas atividades',
    upcoming: 'Próximos posts',
    myRequests: 'Pendências com você',
    plannedContent: 'Conteúdos planejados',
    activeProjects: 'Projetos ativos',
    openRequests: 'Pendências em aberto',
    campaignsSoon: 'Campanhas chegam em breve.',
    nothingHere: 'Nada por aqui.',
    allClear: 'Nada atrasado. Bom trabalho.',
    seeAll: 'Ver tudo',
    noCompany: 'Você ainda não tem acesso a nenhuma empresa.',
  },
  sessions: {
    title: 'Sessões ativas',
    current: 'Esta sessão',
    revoke: 'Encerrar',
    revoking: 'Encerrando…',
    revokeAll: 'Encerrar as outras sessões',
    empty: 'Nenhuma outra sessão ativa.',
    lastActive: 'Última atividade',
    confirmRevoke: 'Encerrar esta sessão? O dispositivo precisará entrar novamente.',
    confirmRevokeAll:
      'Encerrar todas as outras sessões? Os demais dispositivos precisarão entrar novamente.',
  },
  common: {
    save: 'Salvar',
    saving: 'Salvando…',
    cancel: 'Cancelar',
    create: 'Criar',
    creating: 'Criando…',
    edit: 'Editar',
    back: 'Voltar',
    search: 'Buscar',
    filters: 'Filtros',
    all: 'Todos',
    none: '—',
    select: 'Selecione…',
    yes: 'Sim',
    no: 'Não',
    close: 'Fechar',
    copy: 'Copiar',
    copied: 'Copiado.',
    previous: 'Anterior',
    next: 'Próxima',
    pageOf: (page: number, pages: number) => `Página ${page} de ${pages}`,
    resultCount: (total: number) => (total === 1 ? '1 resultado' : `${total} resultados`),
  },
  companies: {
    title: 'Empresas',
    new: 'Nova empresa',
    editTitle: 'Editar empresa',
    newTitle: 'Nova empresa',
    empty: 'Nenhuma empresa por aqui ainda.',
    emptyAdminHint: 'Crie a primeira empresa para começar a organizar projetos e arquivos.',
    emptyMemberHint: 'Quando a agência vincular você a uma empresa, ela aparece aqui.',
    searchPlaceholder: 'Buscar por nome',
    name: 'Nome',
    segment: 'Segmento',
    responsibleName: 'Responsável',
    email: 'E-mail',
    phone: 'Telefone',
    notes: 'Observações',
    status: 'Situação',
    statusActive: 'Ativa',
    statusArchived: 'Arquivada',
    archive: 'Arquivar',
    restore: 'Reativar',
    confirmArchive: 'Arquivar esta empresa? Ela sai das listas ativas, mas nenhum dado é apagado.',
    confirmRestore: 'Reativar esta empresa?',
    created: 'Empresa criada.',
    updated: 'Empresa atualizada.',
  },
  users: {
    title: 'Usuários',
    new: 'Novo usuário',
    editTitle: 'Editar usuário',
    newTitle: 'Novo usuário',
    empty: 'Nenhum usuário encontrado.',
    emptyHint: 'Crie o primeiro usuário para dar acesso à plataforma.',
    searchPlaceholder: 'Buscar por nome ou e-mail',
    name: 'Nome',
    email: 'E-mail',
    role: 'Perfil',
    status: 'Situação',
    statusActive: 'Ativo',
    statusInactive: 'Inativo',
    lastLogin: 'Último acesso',
    neverLoggedIn: 'Nunca acessou',
    initialPassword: 'Senha inicial (opcional)',
    initialPasswordHint: 'Deixe em branco para gerar uma senha automaticamente.',
    created: 'Usuário criado.',
    updated: 'Usuário atualizado.',
    resetPassword: 'Gerar nova senha',
    confirmResetPassword:
      'Gerar uma nova senha temporária? As sessões ativas deste usuário serão encerradas.',
    temporaryPasswordTitle: 'Senha temporária',
    temporaryPasswordWarning:
      'Esta senha aparece apenas uma vez. Copie e entregue ao usuário por um canal seguro.',
    mustChangePassword: 'Precisa trocar a senha no próximo acesso',
  },
  memberships: {
    title: 'Acesso a empresas',
    empty: 'Este usuário ainda não tem acesso a nenhuma empresa.',
    add: 'Vincular empresa',
    company: 'Empresa',
    canManageCampaigns: 'Pode gerenciar campanhas',
    canDeleteCompanyFiles: 'Pode excluir arquivos de outros',
    revoke: 'Remover acesso',
    confirmRevoke:
      'Remover o acesso deste usuário a esta empresa? Ele será desconectado imediatamente.',
    granted: 'Acesso concedido.',
    revoked: 'Acesso removido.',
    updated: 'Permissões atualizadas.',
    noCompaniesLeft: 'Este usuário já tem acesso a todas as empresas.',
    permissionsNote:
      'Estas permissões valem apenas para esta empresa — o mesmo usuário pode ter permissões diferentes em outra.',
  },
  projects: {
    title: 'Projetos',
    new: 'Novo projeto',
    newTitle: 'Novo projeto',
    editTitle: 'Editar projeto',
    empty: 'Nenhum projeto por aqui ainda.',
    emptyHint: 'Crie um projeto para agrupar pastas, arquivos e conteúdos de uma empresa.',
    emptyReadOnlyHint: 'Quando a agência criar projetos para esta empresa, eles aparecem aqui.',
    searchPlaceholder: 'Buscar por nome ou código',
    name: 'Nome',
    code: 'Código',
    company: 'Empresa',
    type: 'Tipo',
    status: 'Situação',
    description: 'Descrição',
    startDate: 'Início',
    endDate: 'Término',
    notes: 'Observações',
    created: 'Projeto criado.',
    updated: 'Projeto atualizado.',
    noPeriod: 'Sem período definido',
  },
  projectTypes: {
    property: 'Imóvel',
    product: 'Produto',
    service: 'Serviço',
    event: 'Evento',
    campaign: 'Campanha',
    internal: 'Interno',
    other: 'Outro',
  },
  projectStatuses: {
    planned: 'Planejado',
    active: 'Ativo',
    paused: 'Pausado',
    completed: 'Concluído',
    archived: 'Arquivado',
  },
  folders: {
    title: 'Pastas',
    new: 'Nova pasta',
    name: 'Nome da pasta',
    root: 'Raiz',
    empty: 'Nenhuma pasta aqui.',
    emptyHint: 'Crie a primeira pasta para organizar os arquivos desta empresa.',
    emptyReadOnlyHint: 'Ainda não há pastas nesta empresa.',
    open: 'Abrir',
    rename: 'Renomear',
    remove: 'Excluir',
    subfolderCount: (count: number) => (count === 1 ? '1 subpasta' : `${count} subpastas`),
    confirmRemove: 'Excluir esta pasta? Ela precisa estar vazia.',
    created: 'Pasta criada.',
    renamed: 'Pasta renomeada.',
    removed: 'Pasta excluída.',
    selectCompany: 'Selecione uma empresa para ver as pastas.',
    noCompanies: 'Você ainda não tem acesso a nenhuma empresa.',
  },
  uploads: {
    title: 'Enviar arquivos',
    choose: 'Escolher arquivos',
    limitHint: (max: string) => `Tamanho máximo por arquivo: ${max}.`,
    pause: 'Pausar',
    resume: 'Retomar',
    cancel: 'Cancelar',
    confirmCancel: 'Cancelar este envio? A parte já enviada será descartada.',
    clearFinished: 'Limpar concluídos',
    progressOf: 'Progresso de',
    state: {
      waiting: 'Aguardando',
      uploading: 'Enviando',
      paused: 'Pausado',
      processing: 'Processando',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      failed: 'Falhou',
    } as Record<string, string>,
  },
  files: {
    title: 'Arquivos',
    empty: 'Nenhuma pasta ou arquivo aqui.',
    emptyHint: 'Envie um arquivo acima ou crie uma pasta para organizar o material.',
    emptyReadOnlyHint: 'Ainda não há nada nesta pasta.',
    searchPlaceholder: 'Buscar pelo nome do arquivo',
    uploadedAt: 'Enviado em',
    download: 'Baixar',
    preparingDownload: 'Preparando…',
    changeStatus: 'Situação',
    remove: 'Excluir',
    confirmRemove: 'Excluir este arquivo? Ele sai das listas, mas continua recuperável.',
    removed: 'Arquivo excluído.',
    statusChanged: 'Situação atualizada.',
    requestDeletion: 'Solicitar exclusão',
    requestDeletionTitle: 'Solicitar exclusão',
    requestDeletionHint:
      'Um administrador da agência vai analisar. Explique por que o arquivo deve ser excluído.',
    reason: 'Motivo',
    sendRequest: 'Enviar solicitação',
    requestSent: 'Solicitação enviada para análise.',
    showNotes: 'Notas',
    hideNotes: 'Ocultar notas',
  },
  fileStatuses: {
    received: 'Recebido',
    in_review: 'Em análise',
    editing: 'Em edição',
    edit_complete: 'Edição concluída',
    approved: 'Aprovado',
    archived: 'Arquivado',
  },
  deletionRequests: {
    title: 'Solicitações de exclusão',
    empty: 'Nenhuma solicitação pendente.',
    emptyHint: 'Solicitações de exclusão feitas pela equipe aparecem aqui para análise.',
    reason: 'Motivo',
    requestedAt: 'Solicitado em',
    approve: 'Aprovar',
    reject: 'Rejeitar',
    reviewNotes: 'Observações da análise',
    confirmApprove: 'Aprovar a exclusão? O item sai das listas, mas continua recuperável.',
    confirmReject: 'Rejeitar esta solicitação?',
    approved: 'Exclusão aprovada.',
    rejected: 'Solicitação rejeitada.',
    statusPending: 'Pendente',
    statusApproved: 'Aprovada',
    statusRejected: 'Rejeitada',
    targetFile: 'Arquivo',
    targetContent: 'Conteúdo',
  },
  calendar: {
    title: 'Calendário',
    newContent: 'Novo conteúdo',
    editContent: 'Editar conteúdo',
    contentTitle: 'Título',
    scheduledAt: 'Data e hora',
    type: 'Tipo',
    productionStatus: 'Produção',
    priority: 'Prioridade',
    responsible: 'Responsável',
    description: 'Descrição',
    duplicate: 'Duplicar',
    duplicatePrompt: 'Para qual data duplicar? (AAAA-MM-DD)',
    duplicated: 'Conteúdo duplicado.',
    invalidDate: 'Data inválida.',
    remove: 'Excluir',
    confirmRemove: 'Excluir este conteúdo? Ele sai do calendário, mas continua recuperável.',
    removed: 'Conteúdo excluído.',
    previous: 'Anterior',
    next: 'Próximo',
    today: 'Hoje',
    viewsLabel: 'Visualizações do calendário',
    empty: 'Nenhum conteúdo planejado.',
    emptyHint: 'Crie o primeiro conteúdo para começar a planejar.',
    emptyDay: 'Nada planejado neste dia.',
    itemCount: (count: number) => (count === 1 ? '1 conteúdo' : `${count} conteúdos`),
    views: {
      month: 'Mês',
      week: 'Semana',
      day: 'Dia',
      list: 'Lista',
    },
    flags: {
      today: 'Hoje',
      overdue: 'Atrasado',
      blocked: 'Aguardando cliente',
    },
    summary: {
      planned: 'Planejados',
      awaitingMaterial: 'Aguardando material',
      inProduction: 'Em produção',
      inReview: 'Em revisão',
      completed: 'Concluídos',
      overdue: 'Atrasados',
      pendingPublication: 'A publicar',
      failedPublication: 'Falhas',
    },
  },
  publications: {
    title: 'Publicações',
    heading: 'Publicação por rede',
    hint: 'Registre manualmente onde este conteúdo foi publicado.',
    network: 'Rede',
    status: 'Situação',
    publishedAt: 'Data da publicação',
    link: 'Link da publicação',
    responsible: 'Responsável',
    notes: 'Observações',
    register: 'Registrar',
    edit: 'Editar registro',
    notTracked: 'Sem registro',
    remove: 'Remover registro',
    confirmRemove: 'Remover o registro desta rede? O histórico de publicação dela é apagado.',
    removed: 'Registro removido.',
    saved: 'Publicação registrada.',
    openLink: 'Abrir publicação',
    lastUpdate: (when: string) => `Atualizado em ${when}`,
    doneCount: (done: number, total: number) => `${done} de ${total} redes publicadas`,
    pendingOnly: 'Somente pendentes',
    empty: 'Nenhuma publicação registrada.',
    emptyHint: 'Abra um conteúdo no calendário para registrar onde ele foi publicado.',
  },
  networks: {
    instagram: 'Instagram',
    facebook: 'Facebook',
    tiktok: 'TikTok',
    youtube_shorts: 'YouTube Shorts',
  },
  publicationStatuses: {
    not_planned: 'Não planejada',
    planned: 'Planejada',
    scheduled: 'Agendada',
    published: 'Publicada',
    not_published: 'Não publicada',
    failed: 'Falhou',
    cancelled: 'Cancelada',
  },
  contentTypes: {
    video: 'Vídeo',
    image: 'Imagem',
    carousel: 'Carrossel',
    story: 'Story',
    reels: 'Reels',
    youtube_short: 'YouTube Short',
    text: 'Texto',
    custom: 'Outro',
  },
  productionStatuses: {
    planned: 'Planejado',
    awaiting_material: 'Aguardando material',
    in_production: 'Em produção',
    in_review: 'Em revisão',
    approved: 'Aprovado',
    completed: 'Concluído',
    cancelled: 'Cancelado',
  },
  comments: {
    title: 'Notas e comentários',
    empty: 'Nenhuma nota ainda. Seja a primeira pessoa a comentar.',
    newComment: 'Nova nota',
    body: 'Texto',
    send: 'Comentar',
    edited: 'editado',
    remove: 'Excluir',
    confirmRemove: 'Excluir esta nota?',
  },
  backups: {
    title: 'Backup do banco',
    explain:
      'Gera uma cópia completa do banco de dados e deixa o arquivo disponível para download por tempo limitado.',
    request: 'Gerar backup',
    requested: 'Backup solicitado. Ele aparece na lista abaixo quando ficar pronto.',
    running: 'Há um backup em andamento.',
    history: 'Backups recentes',
    empty: 'Nenhum backup gerado ainda.',
    download: 'Baixar',
    expiresAt: (when: string) => `Disponível até ${when}`,
    expired: 'Arquivo já removido.',
    downloadedAt: (when: string) => `Baixado em ${when}`,
    size: (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`,
    retention:
      'O arquivo é apagado automaticamente depois do prazo, mesmo que ninguém baixe. Guarde a cópia em outro lugar.',
    confirmTitle: 'Confirme sua senha',
    confirmHint:
      'Gerar um backup exige confirmar a senha, mesmo com a sessão aberta — é uma cópia de tudo.',
    password: 'Senha atual',
    confirm: 'Confirmar e gerar',
    manual: 'No MVP o backup é manual. Backups automáticos e cópias externas entram na Fase 2.',
  },
  backupStatuses: {
    queued: 'Na fila',
    processing: 'Gerando',
    completed: 'Pronto',
    failed: 'Falhou',
  },
  campaigns: {
    title: 'Campanhas',
    new: 'Nova campanha',
    edit: 'Editar campanha',
    name: 'Nome',
    objective: 'Objetivo',
    status: 'Situação',
    platform: 'Plataforma',
    adAccount: 'Conta de anúncios',
    newAdAccount: 'Nova conta de anúncios',
    externalAccountId: 'ID da conta na plataforma',
    externalHint: 'Como está na plataforma. Não conferimos com o anunciante.',
    dailyBudget: 'Orçamento diário',
    totalBudget: 'Orçamento total',
    reportedSpend: 'Investimento informado',
    reportedBalance: 'Saldo informado',
    lastCheckedAt: 'Conferido em',
    responsible: 'Responsável',
    notes: 'Observações',
    visibleToClient: 'Visível para o cliente',
    visibleHint: 'Desmarque para manter esta campanha só com a equipe da agência.',
    hidden: 'Interna',
    create: 'Criar campanha',
    createAccount: 'Criar conta',
    changeNote: 'Motivo da alteração',
    changeNoteHint: 'Fica registrado no histórico junto com o que mudou.',
    saved: 'Campanha atualizada.',
    created: 'Campanha criada.',
    accountCreated: 'Conta de anúncios criada.',
    history: 'Histórico de alterações',
    historyEmpty: 'Nenhuma alteração registrada ainda.',
    from: 'de',
    to: 'para',
    empty: 'Nenhuma campanha cadastrada.',
    emptyHint: 'Cadastre a primeira conta de anúncios para começar.',
    noAccounts: 'Cadastre uma conta de anúncios antes de criar campanhas.',
    needsAttentionOnly: 'Somente as que precisam de atenção',
    /** The spec requires this on screen, not only in the data model. */
    manualNotice:
      'Investimento, saldo e orçamentos são informados manualmente pela equipe. O sistema não lê dados das plataformas de anúncios.',
    manualTag: 'informado manualmente',
    backToList: 'Voltar para campanhas',
    noValue: '—',
  },
  campaignStatuses: {
    active: 'Ativa',
    paused: 'Pausada',
    ended: 'Encerrada',
    with_problem: 'Com problema',
    awaiting_approval: 'Aguardando aprovação',
    needs_attention: 'Precisa de atenção',
  },
  adPlatforms: {
    meta: 'Meta Ads',
    tiktok: 'TikTok Ads',
  },
  campaignFields: {
    name: 'Nome',
    objective: 'Objetivo',
    status: 'Situação',
    adAccountId: 'Conta de anúncios',
    platform: 'Plataforma',
    dailyBudget: 'Orçamento diário',
    totalBudget: 'Orçamento total',
    reportedSpend: 'Investimento informado',
    reportedBalance: 'Saldo informado',
    lastCheckedAt: 'Conferido em',
    visibleToClient: 'Visibilidade para o cliente',
    responsibleUserId: 'Responsável',
    notes: 'Observações',
  },
  notifications: {
    title: 'Notificações',
    open: 'Abrir notificações',
    badge: (count: number) => (count > 99 ? '99+' : String(count)),
    unreadOnly: 'Somente não lidas',
    markAllRead: 'Marcar todas como lidas',
    allRead: 'Tudo marcado como lido.',
    empty: 'Nenhuma notificação por aqui.',
    emptyUnread: 'Você está em dia.',
    openItem: 'Abrir',
    settings: 'Preferências de notificação',
    pushTitle: 'Notificações no celular',
    pushExplain:
      'Podemos avisar você no navegador quando algo precisar da sua atenção — pendências, menções e prazos. Você escolhe quais avisos recebe e pode desligar quando quiser.',
    pushEnable: 'Ativar avisos neste dispositivo',
    pushEnabled: 'Avisos ativados neste dispositivo.',
    pushDenied:
      'O navegador bloqueou os avisos. Libere as notificações para este site nas configurações do navegador.',
    pushUnavailable: 'Este servidor não está configurado para enviar avisos.',
    pushDevices: 'Dispositivos registrados',
    pushRemove: 'Remover',
    pushRemoved: 'Dispositivo removido.',
    pushNoDevices: 'Nenhum dispositivo registrado.',
    pushChannel: 'Receber aviso no dispositivo',
    preferencesHint:
      'A lista de notificações no app recebe tudo. Aqui você escolhe o que também chega como aviso no dispositivo.',
    saved: 'Preferência salva.',
  },
  auditActions: {
    'backup.requested': 'Backup solicitado',
    'backup.completed': 'Backup concluído',
    'backup.failed': 'Backup falhou',
    'backup.downloaded': 'Backup baixado',
    'ad_account.created': 'Conta de anúncios criada',
    'ad_account.updated': 'Conta de anúncios atualizada',
    'campaign.created': 'Campanha criada',
    'campaign.updated': 'Campanha atualizada',
    'campaign.status_changed': 'Situação de campanha alterada',
    'auth.login_succeeded': 'Entrou no sistema',
    'auth.login_failed': 'Falha ao entrar',
    'auth.login_blocked': 'Tentativa de acesso bloqueada',
    'auth.account_locked': 'Conta bloqueada',
    'auth.logout': 'Saiu do sistema',
    'auth.password_changed': 'Senha alterada',
    'auth.reauthenticated': 'Reautenticação confirmada',
    'auth.reauthentication_failed': 'Falha na reautenticação',
    'auth.session_revoked': 'Sessão encerrada',
    'auth.all_sessions_revoked': 'Todas as outras sessões encerradas',
    'company.created': 'Empresa criada',
    'company.updated': 'Empresa atualizada',
    'company.archived': 'Empresa arquivada',
    'company.restored': 'Empresa reativada',
    'user.created': 'Usuário criado',
    'user.updated': 'Usuário atualizado',
    'user.status_changed': 'Situação de usuário alterada',
    'user.password_reset': 'Senha de usuário redefinida',
    'membership.granted': 'Acesso concedido',
    'membership.updated': 'Permissões atualizadas',
    'membership.revoked': 'Acesso removido',
    'branding.updated': 'Identidade visual atualizada',
    'project.created': 'Projeto criado',
    'project.updated': 'Projeto atualizado',
    'project.status_changed': 'Situação de projeto alterada',
    'folder.created': 'Pasta criada',
    'folder.updated': 'Pasta atualizada',
    'folder.deleted': 'Pasta excluída',
    'upload.started': 'Envio iniciado',
    'upload.completed': 'Arquivo enviado',
    'upload.aborted': 'Envio cancelado',
    'upload.expired': 'Envio expirado',
    'file.status_changed': 'Situação de arquivo alterada',
    'file.deleted': 'Arquivo excluído',
    'file.downloaded': 'Arquivo baixado',
    'content.created': 'Conteúdo criado',
    'content.updated': 'Conteúdo atualizado',
    'content.status_changed': 'Situação de conteúdo alterada',
    'content.rescheduled': 'Conteúdo reagendado',
    'content.duplicated': 'Conteúdo duplicado',
    'content.deleted': 'Conteúdo excluído',
    'publication.registered': 'Publicação registrada',
    'publication.updated': 'Publicação atualizada',
    'publication.status_changed': 'Situação de publicação alterada',
    'publication.removed': 'Registro de publicação removido',
    'pending_request.created': 'Pendência criada',
    'pending_request.updated': 'Pendência atualizada',
    'pending_request.status_changed': 'Situação de pendência alterada',
    'pending_request.answered': 'Pendência respondida',
    'comment.created': 'Comentário criado',
    'comment.updated': 'Comentário editado',
    'comment.deleted': 'Comentário excluído',
    'topic.created': 'Acompanhamento criado',
    'topic.updated': 'Acompanhamento atualizado',
    'topic.status_changed': 'Situação de acompanhamento alterada',
    'topic.replied': 'Resposta em acompanhamento',
    'deletion_request.created': 'Exclusão solicitada',
    'deletion_request.approved': 'Exclusão aprovada',
    'deletion_request.rejected': 'Exclusão recusada',
    'security.cross_tenant_access_denied': 'Acesso entre empresas bloqueado',
  },
  notificationTypes: {
    'file.uploaded': 'Novo arquivo enviado',
    'file.status_changed': 'Situação de arquivo alterada',
    'file.response_sent': 'Arquivo recebido em resposta',
    'comment.created': 'Novo comentário ou nota',
    'user.mentioned': 'Você foi mencionado',
    'pending_request.created': 'Nova pendência para você',
    'pending_request.answered': 'Pendência respondida',
    'content.status_changed': 'Situação de conteúdo alterada',
    'content.approval_requested': 'Aprovação solicitada',
    'content.overdue': 'Conteúdo atrasado',
    'publication.status_changed': 'Publicação atualizada',
    'project.changed': 'Projeto alterado',
    'topic.created': 'Novo acompanhamento',
    'topic.replied': 'Resposta em acompanhamento',
    'deletion_request.created': 'Solicitação de exclusão',
    'deletion_request.approved': 'Exclusão aprovada',
    'deletion_request.rejected': 'Exclusão recusada',
    'campaign.status_changed': 'Situação de campanha alterada',
    'campaign.needs_attention': 'Campanha precisa de atenção',
  },
  pendingRequests: {
    title: 'Pendências',
    new: 'Nova pendência',
    edit: 'Editar pendência',
    titleField: 'Título',
    description: 'Descrição',
    descriptionHint: 'O que você precisa e por quê.',
    responsible: 'Responsável',
    project: 'Projeto (opcional)',
    dueDate: 'Prazo',
    priority: 'Prioridade',
    status: 'Situação',
    create: 'Criar pendência',
    respond: 'Responder',
    respondTitle: 'Sua resposta',
    respondHint: 'Anexe um arquivo se precisar enviar material.',
    attach: 'Anexar arquivo',
    attached: (name: string) => `Anexado: ${name}`,
    removeAttachment: 'Remover anexo',
    responded: 'Resposta enviada.',
    saved: 'Pendência atualizada.',
    created: 'Pendência criada.',
    overdue: 'Atrasada',
    awaitingYou: 'Esperando você',
    noDueDate: 'Sem prazo',
    dueOn: (date: string) => `Prazo: ${date}`,
    openedBy: 'Aberta por',
    openedAt: 'Aberta em',
    backToList: 'Voltar para pendências',
    empty: {
      all: 'Nenhuma pendência por aqui.',
      created_by_me: 'Você ainda não abriu nenhuma pendência.',
      awaiting_me: 'Nada esperando por você. ',
      awaiting_others: 'Ninguém está devendo resposta agora.',
      open: 'Nenhuma pendência em aberto.',
      overdue: 'Nenhuma pendência atrasada.',
      completed: 'Nenhuma pendência concluída ainda.',
    } as Record<string, string>,
    views: {
      all: 'Todas',
      created_by_me: 'Que eu abri',
      awaiting_me: 'Esperando por mim',
      awaiting_others: 'Esperando outros',
      open: 'Em aberto',
      overdue: 'Atrasadas',
      completed: 'Concluídas',
    },
    summary: {
      open: 'Abertas',
      awaitingClient: 'Aguardando cliente',
      answered: 'Respondidas',
      inReview: 'Em análise',
      overdue: 'Atrasadas',
      awaitingMe: 'Comigo',
    },
  },
  pendingRequestStatuses: {
    open: 'Aberta',
    awaiting_client: 'Aguardando cliente',
    answered: 'Respondida',
    in_review: 'Em análise',
    completed: 'Concluída',
    cancelled: 'Cancelada',
  },
  topics: {
    title: 'Acompanhamentos',
    new: 'Novo acompanhamento',
    newTitle: 'Novo acompanhamento',
    create: 'Criar acompanhamento',
    titleField: 'Assunto',
    initialMessage: 'Mensagem inicial',
    responsible: 'Responsável',
    priority: 'Prioridade',
    dueDate: 'Prazo',
    viewsLabel: 'Filtros de acompanhamento',
    thread: 'Conversa',
    noReplies: 'Nenhuma resposta ainda.',
    yourReply: 'Sua resposta',
    send: 'Responder',
    resolve: 'Marcar como resolvido',
    confirmResolve: 'Marcar este acompanhamento como resolvido? A conversa será encerrada.',
    closed: 'Este acompanhamento foi encerrado.',
    youAreResponsible: 'Aguardando você',
    you: 'você',
    emptyHint: 'Crie um acompanhamento quando precisar de uma resposta de alguém específico.',
    replyCount: (count: number) => (count === 1 ? '1 resposta' : `${count} respostas`),
    views: {
      all: 'Todos',
      created_by_me: 'Criados por mim',
      awaiting_me: 'Aguardando você',
      awaiting_others: 'Aguardando outros',
      open: 'Em aberto',
      resolved: 'Resolvidos',
    },
    empty: {
      all: 'Nenhum acompanhamento por aqui.',
      created_by_me: 'Você ainda não criou nenhum acompanhamento.',
      awaiting_me: 'Nada aguardando você. Tudo em dia.',
      awaiting_others: 'Nada aguardando resposta de outras pessoas.',
      open: 'Nenhum acompanhamento em aberto.',
      resolved: 'Nenhum acompanhamento resolvido ainda.',
    } as Record<string, string>,
  },
  topicStatuses: {
    open: 'Em aberto',
    awaiting_response: 'Aguardando resposta',
    in_review: 'Em análise',
    resolved: 'Resolvido',
    cancelled: 'Cancelado',
  },
  priorities: {
    low: 'Prioridade baixa',
    medium: 'Prioridade média',
    high: 'Prioridade alta',
  },
  branding: {
    title: 'Identidade visual',
    appName: 'Nome do sistema',
    primaryColor: 'Cor principal',
    secondaryColor: 'Cor secundária',
    loginMessage: 'Mensagem na tela de login',
    assets: 'Imagens da marca',
    logoUrl: 'Logo',
    faviconUrl: 'Favicon',
    loginImageUrl: 'Imagem da tela de login',
    assetHint:
      'Logo até 2 MB (SVG, PNG ou WebP), favicon até 256 KB (PNG ou ICO), imagem de login até 4 MB (JPEG, PNG ou WebP).',
    assetUploaded: 'Imagem atualizada.',
    contrastError: 'Contraste insuficiente com texto branco. Escolha um tom mais escuro.',
    contrastOk: (ratio: string, minimum: number) =>
      `Contraste com texto branco: ${ratio}:1 (mínimo ${minimum}:1).`,
    preview: 'Prévia',
    previewButton: 'Botão principal',
    saved: 'Identidade visual atualizada.',
  },
  roles: {
    agency_admin: 'Administrador da agência',
    agency_manager: 'Gestor da agência',
    client_manager: 'Gestor do cliente',
    contributor: 'Colaborador',
  },
  /** Maps the API's stable English error codes to pt-BR copy (15-api-conventions.md). */
  errors: {
    validation_error: 'Verifique os campos destacados.',
    invalid_credentials: 'E-mail ou senha inválidos.',
    account_locked:
      'Conta temporariamente bloqueada por excesso de tentativas. Aguarde e tente novamente.',
    rate_limited: 'Muitas tentativas. Aguarde alguns minutos e tente novamente.',
    invalid_current_password: 'A senha atual está incorreta.',
    weak_password: 'A nova senha é muito curta.',
    password_unchanged: 'A nova senha deve ser diferente da senha atual.',
    password_change_required: 'Defina uma nova senha antes de continuar.',
    unauthenticated: 'Sua sessão expirou. Entre novamente.',
    account_inactive: 'Esta conta não está ativa. Fale com o administrador.',
    forbidden: 'Você não tem permissão para esta ação.',
    not_found: 'Registro não encontrado.',
    range_too_large: 'O período solicitado é grande demais. Consulte no máximo um ano por vez.',
    topic_closed: 'Este acompanhamento já foi encerrado.',
    responsible_without_access: 'O responsável escolhido não tem acesso a esta empresa.',
    incomplete_relation: 'Informe o tipo e o item relacionado.',
    unknown_file: 'Arquivo anexado não encontrado nesta empresa.',
    file_too_large: 'O arquivo excede o tamanho máximo permitido.',
    file_type_not_allowed: 'Este tipo de arquivo não é aceito.',
    too_many_active_uploads:
      'Há envios demais em andamento nesta empresa. Conclua ou cancele um deles.',
    upload_incomplete: 'O envio ainda não está completo. Retome antes de finalizar.',
    upload_not_resumable: 'Este envio expirou ou foi cancelado. Comece de novo.',
    upload_already_completed: 'Este envio já foi concluído.',
    no_parts_uploaded: 'Nenhuma parte foi enviada.',
    invalid_part_number: 'Número de parte inválido para este envio.',
    unknown_folder: 'Pasta não encontrada nesta empresa.',
    deletion_requires_approval:
      'Você não pode excluir arquivos de outras pessoas. Solicite a exclusão para um administrador aprovar.',
    deletion_request_pending: 'Já existe uma solicitação de exclusão pendente para este item.',
    already_reviewed: 'Esta solicitação já foi analisada.',
    folder_name_taken: 'Já existe uma pasta com este nome neste local.',
    folder_not_empty: 'Esvazie a pasta antes de excluí-la.',
    folder_cycle: 'Uma pasta não pode ser movida para dentro dela mesma.',
    unknown_project: 'Projeto não encontrado nesta empresa.',
    unknown_parent_folder: 'Pasta de destino não encontrada nesta empresa.',
    invalid_date_range: 'A data de término não pode ser anterior ao início.',
    unknown_asset_kind: 'Tipo de imagem de marca desconhecido.',
    file_missing: 'Nenhum arquivo foi enviado.',
    insufficient_contrast:
      'A cor escolhida não tem contraste suficiente com o texto branco. Escolha um tom mais escuro.',
    email_taken: 'Já existe um usuário com este e-mail.',
    membership_exists: 'Este usuário já tem acesso a esta empresa.',
    unknown_company: 'Empresa não encontrada.',
    unknown_user: 'Usuário não encontrado.',
    cannot_change_own_role: 'Você não pode alterar o seu próprio perfil.',
    cannot_deactivate_self: 'Você não pode desativar a sua própria conta.',
    not_planned_with_details: 'Uma rede marcada como "não planejada" não pode ter data nem link.',
    request_closed: 'Esta pendência já foi encerrada.',
    reauthentication_required: 'Confirme sua senha para continuar.',
    backup_already_running: 'Já existe um backup em andamento. Aguarde ele terminar.',
    backup_corrupt: 'O arquivo de backup está incompleto.',
    campaign_management_not_granted:
      'Você não tem permissão para gerenciar campanhas desta empresa.',
    unknown_ad_account: 'Conta de anúncios não encontrada nesta empresa.',
    internal_error: 'Erro interno. Tente novamente.',
    network_error: 'Não foi possível falar com o servidor. Verifique sua conexão.',
  } as Record<string, string>,
} as const;

export function roleLabel(role: string): string {
  return (strings.roles as Record<string, string>)[role] ?? role;
}

export function projectTypeLabel(type: string): string {
  return (strings.projectTypes as Record<string, string>)[type] ?? type;
}

export function projectStatusLabel(status: string): string {
  return (strings.projectStatuses as Record<string, string>)[status] ?? status;
}

export function fileStatusLabel(status: string): string {
  return (strings.fileStatuses as Record<string, string>)[status] ?? status;
}

export function topicStatusLabel(status: string): string {
  return (strings.topicStatuses as Record<string, string>)[status] ?? status;
}

export function topicPriorityLabel(priority: string): string {
  return (strings.priorities as Record<string, string>)[priority] ?? priority;
}

export function contentTypeLabel(type: string): string {
  return (strings.contentTypes as Record<string, string>)[type] ?? type;
}

export function productionStatusLabel(status: string): string {
  return (strings.productionStatuses as Record<string, string>)[status] ?? status;
}

export function networkLabel(network: string): string {
  return (strings.networks as Record<string, string>)[network] ?? network;
}

export function publicationStatusLabel(status: string): string {
  return (strings.publicationStatuses as Record<string, string>)[status] ?? status;
}

/** The audit log is shown to admins on the dashboard, so its codes need copy too. */
export function backupStatusLabel(status: string): string {
  return (strings.backupStatuses as Record<string, string>)[status] ?? status;
}

export function campaignStatusLabel(status: string): string {
  return (strings.campaignStatuses as Record<string, string>)[status] ?? status;
}

export function adPlatformLabel(platform: string): string {
  return (strings.adPlatforms as Record<string, string>)[platform] ?? platform;
}

export function campaignFieldLabel(field: string): string {
  return (strings.campaignFields as Record<string, string>)[field] ?? field;
}

export function auditActionLabel(action: string): string {
  return (strings.auditActions as Record<string, string>)[action] ?? action;
}

export function notificationTypeLabel(type: string): string {
  return (strings.notificationTypes as Record<string, string>)[type] ?? type;
}

export function pendingRequestStatusLabel(status: string): string {
  return (strings.pendingRequestStatuses as Record<string, string>)[status] ?? status;
}

export function pendingRequestEmptyLabel(view: string): string {
  return strings.pendingRequests.empty[view] ?? 'Nenhuma pendência por aqui.';
}

export function topicEmptyLabel(view: string): string {
  return strings.topics.empty[view] ?? 'Nenhum acompanhamento por aqui.';
}
