/**
 * Every piece of user-facing copy lives here (docs/sdd/12-ui-ux-guidelines.md).
 * Phase 1 ships a single locale, but keeping the text out of components means a
 * second locale would be a lookup change rather than a codebase-wide extraction.
 */
export const strings = {
  app: {
    name: 'Agency Hub',
    loading: 'Carregando…',
    retry: 'Tentar novamente',
    genericError: 'Não foi possível concluir a ação. Tente novamente.',
    networkError: 'Não foi possível falar com o servidor. Verifique sua conexão.',
    logout: 'Sair',
  },
  login: {
    title: 'Entrar',
    subtitle: 'Acesse com as credenciais fornecidas pela agência.',
    email: 'E-mail',
    password: 'Senha',
    submit: 'Entrar',
    submitting: 'Entrando…',
    noAccountHelp: 'Esqueceu a senha? Peça uma nova ao administrador da agência.',
  },
  changePassword: {
    title: 'Defina uma nova senha',
    forcedSubtitle: 'Sua senha atual é temporária. Escolha uma nova senha para continuar.',
    currentPassword: 'Senha atual',
    newPassword: 'Nova senha',
    confirmPassword: 'Confirme a nova senha',
    submit: 'Salvar nova senha',
    submitting: 'Salvando…',
    mismatch: 'As senhas não conferem.',
    success: 'Senha alterada com sucesso.',
  },
  home: {
    title: 'Início',
    welcome: (name: string) => `Olá, ${name}.`,
    roleLabel: 'Perfil',
    companiesLabel: 'Empresas com acesso',
    noCompanies: 'Nenhuma empresa vinculada ainda.',
    underConstruction:
      'Os módulos de projetos, arquivos, calendário e campanhas chegam nos próximos estágios.',
  },
  sessions: {
    title: 'Sessões ativas',
    current: 'Esta sessão',
    revoke: 'Encerrar',
    revoking: 'Encerrando…',
    revokeAll: 'Encerrar as outras sessões',
    empty: 'Nenhuma outra sessão ativa.',
    lastActive: 'Última atividade',
    confirmRevoke: 'Encerrar esta sessão? O dispositivo precisará entrar novamente.',
    confirmRevokeAll:
      'Encerrar todas as outras sessões? Os demais dispositivos precisarão entrar novamente.',
  },
  common: {
    save: 'Salvar',
    saving: 'Salvando…',
    cancel: 'Cancelar',
    create: 'Criar',
    creating: 'Criando…',
    edit: 'Editar',
    back: 'Voltar',
    search: 'Buscar',
    filters: 'Filtros',
    all: 'Todos',
    none: '—',
    yes: 'Sim',
    no: 'Não',
    close: 'Fechar',
    copy: 'Copiar',
    copied: 'Copiado.',
    previous: 'Anterior',
    next: 'Próxima',
    pageOf: (page: number, pages: number) => `Página ${page} de ${pages}`,
    resultCount: (total: number) => (total === 1 ? '1 resultado' : `${total} resultados`),
  },
  companies: {
    title: 'Empresas',
    new: 'Nova empresa',
    editTitle: 'Editar empresa',
    newTitle: 'Nova empresa',
    empty: 'Nenhuma empresa por aqui ainda.',
    emptyAdminHint: 'Crie a primeira empresa para começar a organizar projetos e arquivos.',
    emptyMemberHint: 'Quando a agência vincular você a uma empresa, ela aparece aqui.',
    searchPlaceholder: 'Buscar por nome',
    name: 'Nome',
    segment: 'Segmento',
    responsibleName: 'Responsável',
    email: 'E-mail',
    phone: 'Telefone',
    notes: 'Observações',
    status: 'Situação',
    statusActive: 'Ativa',
    statusArchived: 'Arquivada',
    archive: 'Arquivar',
    restore: 'Reativar',
    confirmArchive: 'Arquivar esta empresa? Ela sai das listas ativas, mas nenhum dado é apagado.',
    confirmRestore: 'Reativar esta empresa?',
    created: 'Empresa criada.',
    updated: 'Empresa atualizada.',
  },
  users: {
    title: 'Usuários',
    new: 'Novo usuário',
    editTitle: 'Editar usuário',
    newTitle: 'Novo usuário',
    empty: 'Nenhum usuário encontrado.',
    emptyHint: 'Crie o primeiro usuário para dar acesso à plataforma.',
    searchPlaceholder: 'Buscar por nome ou e-mail',
    name: 'Nome',
    email: 'E-mail',
    role: 'Perfil',
    status: 'Situação',
    statusActive: 'Ativo',
    statusInactive: 'Inativo',
    lastLogin: 'Último acesso',
    neverLoggedIn: 'Nunca acessou',
    initialPassword: 'Senha inicial (opcional)',
    initialPasswordHint: 'Deixe em branco para gerar uma senha automaticamente.',
    created: 'Usuário criado.',
    updated: 'Usuário atualizado.',
    resetPassword: 'Gerar nova senha',
    confirmResetPassword:
      'Gerar uma nova senha temporária? As sessões ativas deste usuário serão encerradas.',
    temporaryPasswordTitle: 'Senha temporária',
    temporaryPasswordWarning:
      'Esta senha aparece apenas uma vez. Copie e entregue ao usuário por um canal seguro.',
    mustChangePassword: 'Precisa trocar a senha no próximo acesso',
  },
  memberships: {
    title: 'Acesso a empresas',
    empty: 'Este usuário ainda não tem acesso a nenhuma empresa.',
    add: 'Vincular empresa',
    company: 'Empresa',
    canManageCampaigns: 'Pode gerenciar campanhas',
    canDeleteCompanyFiles: 'Pode excluir arquivos de outros',
    revoke: 'Remover acesso',
    confirmRevoke:
      'Remover o acesso deste usuário a esta empresa? Ele será desconectado imediatamente.',
    granted: 'Acesso concedido.',
    revoked: 'Acesso removido.',
    updated: 'Permissões atualizadas.',
    noCompaniesLeft: 'Este usuário já tem acesso a todas as empresas.',
    permissionsNote:
      'Estas permissões valem apenas para esta empresa — o mesmo usuário pode ter permissões diferentes em outra.',
  },
  projects: {
    title: 'Projetos',
    new: 'Novo projeto',
    newTitle: 'Novo projeto',
    editTitle: 'Editar projeto',
    empty: 'Nenhum projeto por aqui ainda.',
    emptyHint: 'Crie um projeto para agrupar pastas, arquivos e conteúdos de uma empresa.',
    emptyReadOnlyHint: 'Quando a agência criar projetos para esta empresa, eles aparecem aqui.',
    searchPlaceholder: 'Buscar por nome ou código',
    name: 'Nome',
    code: 'Código',
    company: 'Empresa',
    type: 'Tipo',
    status: 'Situação',
    description: 'Descrição',
    startDate: 'Início',
    endDate: 'Término',
    notes: 'Observações',
    created: 'Projeto criado.',
    updated: 'Projeto atualizado.',
    noPeriod: 'Sem período definido',
  },
  projectTypes: {
    property: 'Imóvel',
    product: 'Produto',
    service: 'Serviço',
    event: 'Evento',
    campaign: 'Campanha',
    internal: 'Interno',
    other: 'Outro',
  },
  projectStatuses: {
    planned: 'Planejado',
    active: 'Ativo',
    paused: 'Pausado',
    completed: 'Concluído',
    archived: 'Arquivado',
  },
  folders: {
    title: 'Pastas',
    new: 'Nova pasta',
    name: 'Nome da pasta',
    root: 'Raiz',
    empty: 'Nenhuma pasta aqui.',
    emptyHint: 'Crie a primeira pasta para organizar os arquivos desta empresa.',
    emptyReadOnlyHint: 'Ainda não há pastas nesta empresa.',
    open: 'Abrir',
    rename: 'Renomear',
    remove: 'Excluir',
    subfolderCount: (count: number) => (count === 1 ? '1 subpasta' : `${count} subpastas`),
    confirmRemove: 'Excluir esta pasta? Ela precisa estar vazia.',
    created: 'Pasta criada.',
    renamed: 'Pasta renomeada.',
    removed: 'Pasta excluída.',
    selectCompany: 'Selecione uma empresa para ver as pastas.',
    noCompanies: 'Você ainda não tem acesso a nenhuma empresa.',
  },
  uploads: {
    title: 'Enviar arquivos',
    choose: 'Escolher arquivos',
    limitHint: (max: string) => `Tamanho máximo por arquivo: ${max}.`,
    pause: 'Pausar',
    resume: 'Retomar',
    cancel: 'Cancelar',
    confirmCancel: 'Cancelar este envio? A parte já enviada será descartada.',
    clearFinished: 'Limpar concluídos',
    progressOf: 'Progresso de',
    state: {
      waiting: 'Aguardando',
      uploading: 'Enviando',
      paused: 'Pausado',
      processing: 'Processando',
      completed: 'Concluído',
      cancelled: 'Cancelado',
      failed: 'Falhou',
    } as Record<string, string>,
  },
  files: {
    title: 'Arquivos',
    empty: 'Nenhuma pasta ou arquivo aqui.',
    emptyHint: 'Envie um arquivo acima ou crie uma pasta para organizar o material.',
    emptyReadOnlyHint: 'Ainda não há nada nesta pasta.',
    searchPlaceholder: 'Buscar pelo nome do arquivo',
    uploadedAt: 'Enviado em',
    download: 'Baixar',
    preparingDownload: 'Preparando…',
    changeStatus: 'Situação',
    remove: 'Excluir',
    confirmRemove: 'Excluir este arquivo? Ele sai das listas, mas continua recuperável.',
    removed: 'Arquivo excluído.',
    statusChanged: 'Situação atualizada.',
    requestDeletion: 'Solicitar exclusão',
    requestDeletionTitle: 'Solicitar exclusão',
    requestDeletionHint:
      'Um administrador da agência vai analisar. Explique por que o arquivo deve ser excluído.',
    reason: 'Motivo',
    sendRequest: 'Enviar solicitação',
    requestSent: 'Solicitação enviada para análise.',
    showNotes: 'Notas',
    hideNotes: 'Ocultar notas',
  },
  fileStatuses: {
    received: 'Recebido',
    in_review: 'Em análise',
    editing: 'Em edição',
    edit_complete: 'Edição concluída',
    approved: 'Aprovado',
    archived: 'Arquivado',
  },
  deletionRequests: {
    title: 'Solicitações de exclusão',
    empty: 'Nenhuma solicitação pendente.',
    emptyHint: 'Solicitações de exclusão feitas pela equipe aparecem aqui para análise.',
    reason: 'Motivo',
    requestedAt: 'Solicitado em',
    approve: 'Aprovar',
    reject: 'Rejeitar',
    reviewNotes: 'Observações da análise',
    confirmApprove: 'Aprovar a exclusão? O item sai das listas, mas continua recuperável.',
    confirmReject: 'Rejeitar esta solicitação?',
    approved: 'Exclusão aprovada.',
    rejected: 'Solicitação rejeitada.',
    statusPending: 'Pendente',
    statusApproved: 'Aprovada',
    statusRejected: 'Rejeitada',
    targetFile: 'Arquivo',
    targetContent: 'Conteúdo',
  },
  calendar: {
    title: 'Calendário',
    newContent: 'Novo conteúdo',
    editContent: 'Editar conteúdo',
    contentTitle: 'Título',
    scheduledAt: 'Data e hora',
    type: 'Tipo',
    productionStatus: 'Produção',
    priority: 'Prioridade',
    responsible: 'Responsável',
    description: 'Descrição',
    duplicate: 'Duplicar',
    duplicatePrompt: 'Para qual data duplicar? (AAAA-MM-DD)',
    duplicated: 'Conteúdo duplicado.',
    invalidDate: 'Data inválida.',
    remove: 'Excluir',
    confirmRemove: 'Excluir este conteúdo? Ele sai do calendário, mas continua recuperável.',
    removed: 'Conteúdo excluído.',
    previous: 'Anterior',
    next: 'Próximo',
    today: 'Hoje',
    viewsLabel: 'Visualizações do calendário',
    empty: 'Nenhum conteúdo planejado.',
    emptyHint: 'Crie o primeiro conteúdo para começar a planejar.',
    emptyDay: 'Nada planejado neste dia.',
    itemCount: (count: number) => (count === 1 ? '1 conteúdo' : `${count} conteúdos`),
    views: {
      month: 'Mês',
      week: 'Semana',
      day: 'Dia',
      list: 'Lista',
    },
    flags: {
      today: 'Hoje',
      overdue: 'Atrasado',
      blocked: 'Aguardando cliente',
    },
    summary: {
      planned: 'Planejados',
      awaitingMaterial: 'Aguardando material',
      inProduction: 'Em produção',
      inReview: 'Em revisão',
      completed: 'Concluídos',
      overdue: 'Atrasados',
    },
  },
  contentTypes: {
    video: 'Vídeo',
    image: 'Imagem',
    carousel: 'Carrossel',
    story: 'Story',
    reels: 'Reels',
    youtube_short: 'YouTube Short',
    text: 'Texto',
    custom: 'Outro',
  },
  productionStatuses: {
    planned: 'Planejado',
    awaiting_material: 'Aguardando material',
    in_production: 'Em produção',
    in_review: 'Em revisão',
    approved: 'Aprovado',
    completed: 'Concluído',
    cancelled: 'Cancelado',
  },
  comments: {
    title: 'Notas e comentários',
    empty: 'Nenhuma nota ainda. Seja a primeira pessoa a comentar.',
    newComment: 'Nova nota',
    body: 'Texto',
    send: 'Comentar',
    edited: 'editado',
    remove: 'Excluir',
    confirmRemove: 'Excluir esta nota?',
  },
  topics: {
    title: 'Acompanhamentos',
    new: 'Novo acompanhamento',
    newTitle: 'Novo acompanhamento',
    create: 'Criar acompanhamento',
    titleField: 'Assunto',
    initialMessage: 'Mensagem inicial',
    responsible: 'Responsável',
    priority: 'Prioridade',
    dueDate: 'Prazo',
    viewsLabel: 'Filtros de acompanhamento',
    thread: 'Conversa',
    noReplies: 'Nenhuma resposta ainda.',
    yourReply: 'Sua resposta',
    send: 'Responder',
    resolve: 'Marcar como resolvido',
    confirmResolve: 'Marcar este acompanhamento como resolvido? A conversa será encerrada.',
    closed: 'Este acompanhamento foi encerrado.',
    youAreResponsible: 'Aguardando você',
    you: 'você',
    emptyHint: 'Crie um acompanhamento quando precisar de uma resposta de alguém específico.',
    replyCount: (count: number) => (count === 1 ? '1 resposta' : `${count} respostas`),
    views: {
      all: 'Todos',
      created_by_me: 'Criados por mim',
      awaiting_me: 'Aguardando você',
      awaiting_others: 'Aguardando outros',
      open: 'Em aberto',
      resolved: 'Resolvidos',
    },
    empty: {
      all: 'Nenhum acompanhamento por aqui.',
      created_by_me: 'Você ainda não criou nenhum acompanhamento.',
      awaiting_me: 'Nada aguardando você. Tudo em dia.',
      awaiting_others: 'Nada aguardando resposta de outras pessoas.',
      open: 'Nenhum acompanhamento em aberto.',
      resolved: 'Nenhum acompanhamento resolvido ainda.',
    } as Record<string, string>,
  },
  topicStatuses: {
    open: 'Em aberto',
    awaiting_response: 'Aguardando resposta',
    in_review: 'Em análise',
    resolved: 'Resolvido',
    cancelled: 'Cancelado',
  },
  priorities: {
    low: 'Prioridade baixa',
    medium: 'Prioridade média',
    high: 'Prioridade alta',
  },
  branding: {
    title: 'Identidade visual',
    appName: 'Nome do sistema',
    primaryColor: 'Cor principal',
    secondaryColor: 'Cor secundária',
    loginMessage: 'Mensagem na tela de login',
    assets: 'Imagens da marca',
    logoUrl: 'Logo',
    faviconUrl: 'Favicon',
    loginImageUrl: 'Imagem da tela de login',
    assetHint:
      'Logo até 2 MB (SVG, PNG ou WebP), favicon até 256 KB (PNG ou ICO), imagem de login até 4 MB (JPEG, PNG ou WebP).',
    assetUploaded: 'Imagem atualizada.',
    contrastError: 'Contraste insuficiente com texto branco. Escolha um tom mais escuro.',
    contrastOk: (ratio: string, minimum: number) =>
      `Contraste com texto branco: ${ratio}:1 (mínimo ${minimum}:1).`,
    preview: 'Prévia',
    previewButton: 'Botão principal',
    saved: 'Identidade visual atualizada.',
  },
  roles: {
    agency_admin: 'Administrador da agência',
    agency_manager: 'Gestor da agência',
    client_manager: 'Gestor do cliente',
    contributor: 'Colaborador',
  },
  /** Maps the API's stable English error codes to pt-BR copy (15-api-conventions.md). */
  errors: {
    validation_error: 'Verifique os campos destacados.',
    invalid_credentials: 'E-mail ou senha inválidos.',
    account_locked:
      'Conta temporariamente bloqueada por excesso de tentativas. Aguarde e tente novamente.',
    rate_limited: 'Muitas tentativas. Aguarde alguns minutos e tente novamente.',
    invalid_current_password: 'A senha atual está incorreta.',
    weak_password: 'A nova senha é muito curta.',
    password_unchanged: 'A nova senha deve ser diferente da senha atual.',
    password_change_required: 'Defina uma nova senha antes de continuar.',
    unauthenticated: 'Sua sessão expirou. Entre novamente.',
    account_inactive: 'Esta conta não está ativa. Fale com o administrador.',
    forbidden: 'Você não tem permissão para esta ação.',
    not_found: 'Registro não encontrado.',
    range_too_large: 'O período solicitado é grande demais. Consulte no máximo um ano por vez.',
    topic_closed: 'Este acompanhamento já foi encerrado.',
    responsible_without_access: 'O responsável escolhido não tem acesso a esta empresa.',
    incomplete_relation: 'Informe o tipo e o item relacionado.',
    unknown_file: 'Arquivo anexado não encontrado nesta empresa.',
    file_too_large: 'O arquivo excede o tamanho máximo permitido.',
    file_type_not_allowed: 'Este tipo de arquivo não é aceito.',
    too_many_active_uploads:
      'Há envios demais em andamento nesta empresa. Conclua ou cancele um deles.',
    upload_incomplete: 'O envio ainda não está completo. Retome antes de finalizar.',
    upload_not_resumable: 'Este envio expirou ou foi cancelado. Comece de novo.',
    upload_already_completed: 'Este envio já foi concluído.',
    no_parts_uploaded: 'Nenhuma parte foi enviada.',
    invalid_part_number: 'Número de parte inválido para este envio.',
    unknown_folder: 'Pasta não encontrada nesta empresa.',
    deletion_requires_approval:
      'Você não pode excluir arquivos de outras pessoas. Solicite a exclusão para um administrador aprovar.',
    deletion_request_pending: 'Já existe uma solicitação de exclusão pendente para este item.',
    already_reviewed: 'Esta solicitação já foi analisada.',
    unsupported_target: 'Ainda não é possível solicitar exclusão deste tipo de item.',
    folder_name_taken: 'Já existe uma pasta com este nome neste local.',
    folder_not_empty: 'Esvazie a pasta antes de excluí-la.',
    folder_cycle: 'Uma pasta não pode ser movida para dentro dela mesma.',
    unknown_project: 'Projeto não encontrado nesta empresa.',
    unknown_parent_folder: 'Pasta de destino não encontrada nesta empresa.',
    invalid_date_range: 'A data de término não pode ser anterior ao início.',
    unknown_asset_kind: 'Tipo de imagem de marca desconhecido.',
    file_missing: 'Nenhum arquivo foi enviado.',
    insufficient_contrast:
      'A cor escolhida não tem contraste suficiente com o texto branco. Escolha um tom mais escuro.',
    email_taken: 'Já existe um usuário com este e-mail.',
    membership_exists: 'Este usuário já tem acesso a esta empresa.',
    unknown_company: 'Empresa não encontrada.',
    unknown_user: 'Usuário não encontrado.',
    cannot_change_own_role: 'Você não pode alterar o seu próprio perfil.',
    cannot_deactivate_self: 'Você não pode desativar a sua própria conta.',
    internal_error: 'Erro interno. Tente novamente.',
    network_error: 'Não foi possível falar com o servidor. Verifique sua conexão.',
  } as Record<string, string>,
} as const;

export function roleLabel(role: string): string {
  return (strings.roles as Record<string, string>)[role] ?? role;
}

export function projectTypeLabel(type: string): string {
  return (strings.projectTypes as Record<string, string>)[type] ?? type;
}

export function projectStatusLabel(status: string): string {
  return (strings.projectStatuses as Record<string, string>)[status] ?? status;
}

export function fileStatusLabel(status: string): string {
  return (strings.fileStatuses as Record<string, string>)[status] ?? status;
}

export function topicStatusLabel(status: string): string {
  return (strings.topicStatuses as Record<string, string>)[status] ?? status;
}

export function topicPriorityLabel(priority: string): string {
  return (strings.priorities as Record<string, string>)[priority] ?? priority;
}

export function contentTypeLabel(type: string): string {
  return (strings.contentTypes as Record<string, string>)[type] ?? type;
}

export function productionStatusLabel(status: string): string {
  return (strings.productionStatuses as Record<string, string>)[status] ?? status;
}

export function topicEmptyLabel(view: string): string {
  return strings.topics.empty[view] ?? 'Nenhum acompanhamento por aqui.';
}
